[phases.setup]
nixPkgs = ["python311", "ffmpeg", "poppler_utils"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p ml_models"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
